---
- name: "update apt packages."
  become: yes
  apt:
    update_cache: yes

- name: "upgrade packages"
  become: yes
  apt:
    upgrade: yes

- name: remove dependencies that are no longer required
  become: yes
  apt:
    autoremove: yes

- name: Creates directory
  file:
    path: ~/web
    state: directory

#- name: Executing node
#  shell: |
#    curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
#    sudo mv /tmp/eksctl /usr/local/bin

   - name: Download eksctl using get_url
     become: yes
     get_url:
       url: "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz"
       dest: /tmp
       cd /tmp
       tar xz -C /tmp
       sudo mv /tmp/eksctl /usr/local/bin
