- name: Transfer Zipped file
  copy:
    src: /root/project/backend.tgz
    dest: /home/ubuntu/

- name: Untar file
  shell: |
    cd /home/ubuntu
    tar -xvzf backend.tgz

- name: "Update npm"
  become: true
  shell: |
    cd /home/ubuntu/backend
    npm install -g npm@6.13.4

- name: "install package dependencies"
  #become: true
  shell: |
    cd /home/ubuntu/backend
    ls -la
    npm install
    #npm audit fix --audit-level=critical --force

- name: "build package"
  #become: true
  shell: |
    cd /home/ubuntu/backend
    npm run build

- name: Executing node
  #become: true
  shell: |
    cd /home/ubuntu/backend
    pm2 start npm --name backend -- start
    pm2 ls
