version: 2.1
orbs:
  slack: circleci/slack@4.1

jobs:
  configure-infrastructure:
    docker:
      - image: python:3.7-alpine3.11
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a3:27:68:1c:b4:68:20:dd:2a:d7:5e:79:3d:06:77:46"]

      - attach_workspace:
          at: ~/project/

      - run:
          name: Install dependencies
          command: |
            apk add --update ansible
            pip install awscli
            ls -la ~/project
            ls -la ~/project/.circleci/ansible
            cat ~/project/.circleci/ansible/inventory.txt

      - run:
          name: configure server
          command: |
            cd ~/project/.circleci/ansible
            aws ec2 describe-instances --query 'Reservations[*].Instances[*].PublicIpAddress' --filters "Name=tag:Name,Values=uda-capstone" --region=us-east-1 --output text >> inventory.txt >> inventory.txt
            cat inventory.txt

            ansible-playbook -i inventory.txt server-setup.yml
            #exit 1

  linting:
    docker:
      - image: python:3.7.3-stretch

    working_directory: ~/project

    steps:
      - checkout

      - run:
          name: checking paths
          command: |
            echo 'path is:' ${pwd}
            echo 'the path is:'
            pwd
            ls -la
            ls -la ~/project/.circleci/dockerstuff


      # Download and cache dependencies
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "~/project/.circleci/dockerstuff/requirements.txt" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - run:
          name: install dependencies
          command: |
            cd ~/project/.circleci/dockerstuff
            python3 -m venv venv
            ls -l venv
            ls -l venv/bin
            . venv/bin/activate
            apt-get -y install make
            make --version
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
              chmod +x /bin/hadolint

      - save_cache:
            paths:
              - ./venv
            key: v1-dependencies-{{ checksum "~/project/.circleci/dockerstuff/requirements.txt" }}

      # run lint!
      - run:
          name: Run lint
          command: |
            cd ~/project/.circleci/dockerstuff
            . venv/bin/activate
            make install
            make lint
            exit 1
      - slack/notify:
          event: fail
          template: basic_fail_1



  create-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/dockerstuff
            ls -la
            sh run_docker.sh
      - run:
          name: get docker container ID
          command: |
            docker ps -aq
      - run:
          name: commit container
          command: |
            docker container commit $(docker ps -qa) joepub/capstone
      - run:
          name: Upload to repo
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker push joepub/capstone




workflows:
  default:
    jobs:
      - linting
      #- create-docker
      #- configure-infrastructure
