version: 2.1
orbs:
  slack: circleci/slack@4.1
  #aws-eks: circleci/aws-eks@x.y
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  minikube-setup:
    machine:
      image: ubuntu-2004:202010-01
#      working_directory: ~/project
    steps:
      - checkout
      - run:
          name: install update OS
          command: |
            sudo apt update
      - run:
          name: install minikube
          command: |
            curl -LO https://storage.googleapis.com/minikube/releases/latest/minikube_latest_amd64.deb
            sudo dpkg -i minikube_latest_amd64.deb
      - run:
          name: install kubectl
          command: |
            curl -Lo kubectl https://storage.googleapis.com/kubernetes-release/release/v1.19.0/bin/linux/amd64/kubectl && chmod +x kubectl && sudo mv kubectl /usr/local/bin/
      - run:
          name: start minikube
          command: |
            minikube start --vm-driver=docker --kubernetes-version=v1.19.0
            minikube addons enable registry

      - run:
          name: test kube
          command: kubectl config view
      - run:
          name: download-container 1
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 2
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 3
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 4
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 5
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 6
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 7
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 8
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - run:
          name: download-container 9
          command: |
            pwd
            cd /home/circleci/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - slack/notify:
          event: fail
          template: basic_fail_1
      - run:
          name: run app
          command: |
            pwd
            sleep 3m
            kubectl port-forward pod/capstone --address 0.0.0.0 8000:8000

#---------------------- job ?? --------------------------
  run-app:
    machine: true
    steps:
      - checkout
      - run:
          name: download-container
          command: |
            cd ~/project/.circleci/dockerstuff
            ls -la
            sh run_k8s.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

#---------------------- Job ??--------------


workflows:
  default:
    jobs:
      - minikube-setup:
          filters:
            branches:
              only: minikube
