version: 2.1
jobs:
  create-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: create docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/dockerstuff
            ls -la

      - run:
          name: build docker image
          command: |
            ls -la
            cd ~/project/.circleci/dockerstuff
            sh run_docker.sh
      - run:
          name: get docker container ID
          command: |
            docker ps -aq
      - run:
          name: get docker container ID
          command: |
            docker container commit $(docker ps -qa) joepub/capstone
            docker push joepub/capstone




workflows:
  default:
    jobs:
      - create-docker
