version: 2.1
orbs:
  slack: circleci/slack@4.1
jobs:
  docker-stuff:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/dockerstuff
            ls -la
            exit 1
            sh run_docker.sh
      - slack/notify:
          event: fail
          template: basic_fail_1

  docker-rest:
    machine: true
    steps:
      - checkout
      - run:
          name: get docker container ID
          command: |
            docker ps -aq
      - run:
          name: commit container
          command: |
            docker container commit $(docker ps -qa) joepub/capstone
      - run:
          name: Upload to repo
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker push joepub/capstone

#  aws-eks:

#  k8s-stuff:
#    machine: true
#    steps:
#      - checkout
#      - run:
#          name: download container
#          command: |
#            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
#            docker push joepub/capstone



workflows:
  capstone-project:
    jobs:
      - docker-stuff
