version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  aws-ecr: circleci/aws-ecr@6.15.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  show-cluster:
    executor: aws-eks/python3
    steps:
      - run:
          name: show variables
          command: |
            CLUSTER_NAME="my-eks-demo"
            echo ${AWS_REGION}
            echo {AWS_PROFILE}
            VERBOSE="3"
            #if [ -n "${CLUSTER_NAME}" ]; then
            #  set -- "$@" --name "${CLUSTER_NAME}"
            #fi
            #if [ -n "${AWS_REGION}" ]; then
            #  set -- "$@" --region "${AWS_REGION}"
            #fi
            #if [ -n "${AWS_PROFILE}" ]; then
            #  set -- "$@" --profile="${AWS_PROFILE}"
            #fi
            #set -- "$@" --verbose ${VERBOSE}

            echo ${@}
workflows:
  main:
    jobs:
      - show-cluster
