version: 2.1
jobs:
  create-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: create docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/files
            ls -la


workflows:
  default:
    jobs:
      - create-docker
