version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  aws-ecr: circleci/aws-ecr@3.1.0
  kubernetes: circleci/kubernetes@0.4.0

jobs:
  eks-install:
    machine:
      image: ubuntu-2004:202010-01
    steps:
      - checkout
      - add_ssh_keys:
          fingerprints: ["a3:27:68:1c:b4:68:20:dd:2a:d7:5e:79:3d:06:77:46"]
      - run:
          name: install eksctl
          command: |
            sudo apt update -y
            sudo apt install -y apt-utils
            sudo apt install curl -y
            sudo apt install awscli
            #sudo apt install ansible -y
            cd ~/project/.circleci/ansible
            ls -la

            curl --silent --location "https://github.com/weaveworks/eksctl/releases/latest/download/eksctl_$(uname -s)_amd64.tar.gz" | tar xz -C /tmp
            sudo mv /tmp/eksctl /usr/local/bin
            sudo eksctl version

            sudo eksctl create cluster #--version 1.17 --name demo-cluster --region us-east-1 --nodegroup #name linux-nodes --node-type t2.micro --nodes 2

            #ansible-playbook configure-eks-server.yml


#            kubectl get services


workflows:
  deployment:
    jobs:
      - eks-install
