version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  aws-ecr: circleci/aws-ecr@6.15.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  show-cluster:
    executor: aws-eks/python3
    steps:
      - checkout
      - run:
          name: show variables
          command: |
            CLUSTER_NAME="my-eks-demo"

            VERBOSE="3"
            if [ -n "${CLUSTER_NAME}" ]; then
              set -- "$@" --name "${CLUSTER_NAME}"
              echo "cluster name: " ${CLUSTER_NAME}
            fi
            if [ -n "${AWS_REGION}" ]; then
              set -- "$@" --region "${AWS_REGION}"
              echo "aws region: " ${AWS_REGION}
            fi
            if [ -n "${AWS_PROFILE}" ]; then
              set -- "$@" --profile="${AWS_PROFILE}"
              echo "aws profile: " ${AWS_PROFILE}
            fi
            set -- "$@" --verbose ${VERBOSE}

            echo "my variables: " ${@}
workflows:
  main:
    jobs:
      - show-cluster
