version: 2.1
jobs:
  create-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: build docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/dockerstuff
            ls -la
            sh run_docker.sh
      - run:
          name: get docker container ID
          command: |
            docker ps -aq
      - run:
          name: commit container
          command: |
            docker container commit $(docker ps -qa) joepub/capstone
      - run:
          name: Upload to repo
          command: |
            echo "$DOCKER_PASSWORD" | docker login --username $DOCKER_LOGIN --password-stdin
            docker push joepub/capstone




workflows:
  default:
    jobs:
      - create-docker
