version: 2.1
jobs:
  create-docker:
    machine: true
    steps:
      - checkout
      - run:
          name: create docker image
          command: |
            pwd
            ls -al
            cd ~/project/.circleci/dockerstuff
            ls -la

      - run:
          name: build docker image
          command: |
            ls -la
            cd ~/project/.circleci/dockerstuff
            #docker build --tag=hello .
            #docker image ls
            sh run_docker.sh


workflows:
  default:
    jobs:
      - create-docker
