version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  aws-ecr: circleci/aws-ecr@6.15.3
  kubernetes: circleci/kubernetes@0.11.2

jobs:
  show-cluster:
    executor: aws-eks/python3
    steps:
      - checkout
      - run:
          name: show variables
          command: |
            pwd
            ls -la
            #cd ~/k8s

workflows:
  main:
    jobs:
      - show-cluster
