version: 2.1
orbs:
  aws-eks: circleci/aws-eks@1.0.3
  kubernetes: circleci/kubernetes@0.4.0

  jobs:
  test-cluster:
    executor: aws-eks/python3
    parameters:
      demo-cluster:
        description: |
          demo cluster setup
        type: string
    steps:
      - kubernetes/install
      - aws-eks/update-kubeconfig-with-authenticator:
          cluster-name: << parameters.demo-cluster >>
      - run:
          command: |
            name: Test cluster
            kubectl get services


workflows:
  default:
    jobs:
      - test-cluster
